spring:
  application:
    name: literature-assistant
  
  # Jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  # 数据源配置
  datasource:
    url: jdbc:h2:file:./data/literature_assistant   # 持久化到项目目录下
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  sql:
    init:
      schema-locations: classpath:db.sql
      mode: always

# Knife4j 配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表

# 服务器配置
server:
  port: 8086
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 日志配置
logging:
  level:
    com.yuyuan.literature: debug
    org.springframework.web: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/literature-assistant.log

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

# 文献助手配置
literature:
  # 文件存储配置
  file:
    upload-path: ./uploads/documents
    max-file-size: 10MB
    allowed-extensions: pdf,doc,docx,md,markdown
  
  # AI 配置
  ai:
    # Kimi AI 配置
    base-url: https://api.moonshot.cn/v1
    model: kimi-k2-turbo-preview
    max-tokens: 20480
    temperature: 0.7
    timeout: 60000
    
    # 系统提示词文件路径配置
    system-prompt-file: classpath:prompts/literature-guide-system-prompt.txt
    classification-prompt-file: classpath:prompts/literature-classification-system-prompt.txt